Repository communicode/communikey-backend, pull requests merged in 2018-05, with the labels that each got.

#7 Update spring boot
  pom.xml
  src/main/java/de/communicode/communikey/ApplicationDataBootstrap.java
  src/main/java/de/communicode/communikey/config/CommunikeyProperties.java
  src/main/java/de/communicode/communikey/config/DataSourceConfig.java
  src/main/java/de/communicode/communikey/config/DateTimeFormatConfig.java
  src/main/java/de/communicode/communikey/config/JacksonConfig.java
  src/main/java/de/communicode/communikey/config/Swagger2Config.java
  src/main/java/de/communicode/communikey/config/WebSocketConfig.java
  src/main/java/de/communicode/communikey/domain/AbstractEntity.java
  src/main/java/de/communicode/communikey/domain/Key.java
  src/main/java/de/communicode/communikey/domain/KeyCategory.java
  src/main/java/de/communicode/communikey/domain/Tag.java
  src/main/java/de/communicode/communikey/domain/User.java
  src/main/java/de/communicode/communikey/domain/UserEncryptedPassword.java
  src/main/java/de/communicode/communikey/domain/UserGroup.java
  src/main/java/de/communicode/communikey/exception/GlobalControllerExceptionHandler.java
  src/main/java/de/communicode/communikey/security/SecurityAuditorAware.java
  src/main/java/de/communicode/communikey/service/KeyCategoryService.java
  src/main/java/de/communicode/communikey/service/KeyService.java
  src/main/java/de/communicode/communikey/service/TagService.java
  src/main/java/de/communicode/communikey/service/UserGroupService.java
  src/main/java/de/communicode/communikey/service/UserService.java
  src/main/java/de/communicode/communikey/service/payload/EncryptionJobAbortPayload.java
  src/main/java/de/communicode/communikey/service/payload/EncryptionJobPayload.java
  src/main/java/de/communicode/communikey/service/payload/EncryptionJobStatusPayload.java
  src/main/java/de/communicode/communikey/service/payload/KeyCategoryPayload.java
  src/main/java/de/communicode/communikey/service/payload/KeyPayload.java
  src/main/java/de/communicode/communikey/service/payload/KeyPayloadEncryptedPasswords.java
  src/main/java/de/communicode/communikey/service/payload/TagPayload.java
  src/main/java/de/communicode/communikey/service/payload/UserCreationPayload.java
  src/main/java/de/communicode/communikey/service/payload/UserCredentialPayload.java
  src/main/java/de/communicode/communikey/service/payload/UserPasswordResetPayload.java
  src/main/java/de/communicode/communikey/service/payload/UserPayload.java
  src/main/java/de/communicode/communikey/service/payload/UserPublicKeyResetPayload.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yaml
  src/test/java/de/communicode/communikey/IntegrationBaseTest.java
  src/test/resources/application-test.yml
Labels: priority-high, scope-security, type-improvement

#14 Migrate to Gradle
  .gitignore
  build.gradle
  config/checkstyle/communicode-style-guide-1.1.xml
  pom.xml
  settings.gradle
  src/integration-test/java/de/communicode/communikey/CommunikeyIntegrationTest.java
  src/integration-test/java/de/communicode/communikey/IntegrationBaseTest.java
  src/integration-test/java/de/communicode/communikey/api/ApiRootIt.java
  src/integration-test/java/de/communicode/communikey/api/AuthorityApiIt.java
  src/integration-test/java/de/communicode/communikey/api/KeyApiIt.java
  src/integration-test/java/de/communicode/communikey/api/KeyCategoryApiIt.java
  src/integration-test/java/de/communicode/communikey/api/TagApiIt.java
  src/integration-test/java/de/communicode/communikey/api/UserApiIt.java
  src/integration-test/java/de/communicode/communikey/api/UserGroupApiIt.java
  src/integration-test/resources/application-integration-test.yml
  src/main/java/de/communicode/communikey/config/util/DefaultProfileUtil.java
  src/test/java/de/communicode/communikey/api/KeyCategoryApiIT.java
  src/test/java/de/communicode/communikey/api/TagApiIT.java
  src/test/java/de/communicode/communikey/api/UserApiIT.java
  src/test/java/de/communicode/communikey/api/UserGroupApiIT.java
Labels: context-workflow, scope-maintainability, type-improvement

#16 log4j2 configuration for production mode
  src/main/resources/application.yaml
  src/main/resources/log4j2-dev.yml
  src/main/resources/log4j2.yml
  src/test/resources/application-test.yml
Labels: scope-maintainability, type-improvement

#17 GitHub "code owners" feature
  .github/CODEOWNERS
Labels: context-documentation, context-workflow, scope-maintainability, type-task

#18 GitHub Open Source Community Standards
  .mailmap
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: context-documentation, context-workflow, scope-maintainability, type-improvement

#19 GitHub issue- and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bugs.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: context-documentation, context-workflow, scope-maintainability, status-blocked, type-task
